Backend: Vivado
Board: null
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: '1'
IOType: io_parallel
KerasH5: KERAS_3layer_weights.h5
KerasJson: KERAS_3layer.json
OutputDir: my-hls-test
ProjectName: myproject
Stamp: ddd6FaD6
XilinxPart: xcku115-flvb2104-2-i
