Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    bn_conv_0:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    bn_conv_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    bn_conv_2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    bn_conv_3:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    bn_conv_4:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    bn_dense_0:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    bn_dense_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_0:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_0_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_1_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_2_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_3:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_3_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_4:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_4_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_act_0:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_act_1:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_act_2:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_act_3:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    conv_act_4:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    dense_0:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    dense_0_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    dense_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    dense_1_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    dense_act_0:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    dense_act_1:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    flatten:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    input_1:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    output_dense:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    output_dense_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    output_softmax:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Stable
      Trace: false
    pool_0:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    pool_1:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
    pool_4:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
KerasModel: !keras_model 'AlexNet_Cifar10_Keras/keras_model.h5'
OutputDir: AlexNet_Cifar10_Keras
Part: xczu7ev-ffvc1156-2-e
ProjectName: AlexNet_Cifar10_Keras
Stamp: 02EcAc4b
