// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer23_out_dout,
        layer23_out_num_data_valid,
        layer23_out_fifo_cap,
        layer23_out_empty_n,
        layer23_out_read,
        layer24_out_din,
        layer24_out_num_data_valid,
        layer24_out_fifo_cap,
        layer24_out_full_n,
        layer24_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] layer23_out_dout;
input  [6:0] layer23_out_num_data_valid;
input  [6:0] layer23_out_fifo_cap;
input   layer23_out_empty_n;
output   layer23_out_read;
output  [255:0] layer24_out_din;
input  [4:0] layer24_out_num_data_valid;
input  [4:0] layer24_out_fifo_cap;
input   layer24_out_full_n;
output   layer24_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer23_out_read;
reg layer24_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln55_reg_2034;
reg   [0:0] icmp_ln55_reg_2034_pp0_iter1_reg;
reg   [0:0] and_ln55_2_reg_2056;
reg    ap_predicate_op300_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_280_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] sY_4;
reg   [31:0] pY_4;
reg   [31:0] pX_4;
reg   [31:0] sX_4;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_167;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_168;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_169;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_170;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_171;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_172;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_173;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_174;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_175;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_176;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_177;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_178;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_179;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_180;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_181;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_182;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_183;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_184;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_185;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_186;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_187;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_188;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_189;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_190;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_191;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_192;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_193;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_194;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_q0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_ce0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_we0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_d0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_q0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_ce0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_we0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_d0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_q0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_ce0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_we0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_d0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_q0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_ce0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_we0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_d0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_q0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_ce0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_we0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_d0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_q0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_ce0;
reg    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_we0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_d0;
wire   [15:0] p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_q0;
reg    layer23_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer24_out_blk_n;
reg   [0:0] icmp_ln109_reg_2030;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln55_fu_296_p2;
wire   [0:0] icmp_ln55_5_fu_310_p2;
reg   [0:0] icmp_ln55_5_reg_2038;
wire   [0:0] icmp_ln55_6_fu_316_p2;
reg   [0:0] icmp_ln55_6_reg_2043;
wire   [0:0] icmp_ln76_fu_328_p2;
reg   [0:0] icmp_ln76_reg_2048;
wire   [0:0] icmp_ln80_fu_382_p2;
reg   [0:0] icmp_ln80_reg_2052;
wire   [0:0] and_ln55_2_fu_1053_p2;
wire   [15:0] select_ln65_fu_1071_p3;
reg   [15:0] select_ln65_reg_2060;
wire   [15:0] select_ln65_204_fu_1091_p3;
reg   [15:0] select_ln65_204_reg_2066;
wire   [15:0] select_ln65_206_fu_1111_p3;
reg   [15:0] select_ln65_206_reg_2072;
wire   [15:0] select_ln65_207_fu_1131_p3;
reg   [15:0] select_ln65_207_reg_2078;
wire   [15:0] select_ln65_209_fu_1151_p3;
reg   [15:0] select_ln65_209_reg_2084;
wire   [15:0] select_ln65_210_fu_1171_p3;
reg   [15:0] select_ln65_210_reg_2090;
wire   [15:0] select_ln65_212_fu_1191_p3;
reg   [15:0] select_ln65_212_reg_2096;
wire   [15:0] select_ln65_213_fu_1211_p3;
reg   [15:0] select_ln65_213_reg_2102;
wire   [15:0] select_ln65_215_fu_1231_p3;
reg   [15:0] select_ln65_215_reg_2108;
wire   [15:0] select_ln65_216_fu_1251_p3;
reg   [15:0] select_ln65_216_reg_2114;
wire   [15:0] select_ln65_218_fu_1271_p3;
reg   [15:0] select_ln65_218_reg_2120;
wire   [15:0] select_ln65_219_fu_1291_p3;
reg   [15:0] select_ln65_219_reg_2126;
wire   [15:0] select_ln65_221_fu_1311_p3;
reg   [15:0] select_ln65_221_reg_2132;
wire   [15:0] select_ln65_222_fu_1331_p3;
reg   [15:0] select_ln65_222_reg_2138;
wire   [15:0] select_ln65_224_fu_1351_p3;
reg   [15:0] select_ln65_224_reg_2144;
wire   [15:0] select_ln65_225_fu_1371_p3;
reg   [15:0] select_ln65_225_reg_2150;
wire   [15:0] select_ln65_227_fu_1391_p3;
reg   [15:0] select_ln65_227_reg_2156;
wire   [15:0] select_ln65_228_fu_1411_p3;
reg   [15:0] select_ln65_228_reg_2162;
wire   [15:0] select_ln65_230_fu_1431_p3;
reg   [15:0] select_ln65_230_reg_2168;
wire   [15:0] select_ln65_231_fu_1451_p3;
reg   [15:0] select_ln65_231_reg_2174;
wire   [15:0] select_ln65_233_fu_1471_p3;
reg   [15:0] select_ln65_233_reg_2180;
wire   [15:0] select_ln65_234_fu_1491_p3;
reg   [15:0] select_ln65_234_reg_2186;
wire   [15:0] select_ln65_236_fu_1511_p3;
reg   [15:0] select_ln65_236_reg_2192;
wire   [15:0] select_ln65_237_fu_1531_p3;
reg   [15:0] select_ln65_237_reg_2198;
wire   [15:0] select_ln65_239_fu_1551_p3;
reg   [15:0] select_ln65_239_reg_2204;
wire   [15:0] select_ln65_240_fu_1571_p3;
reg   [15:0] select_ln65_240_reg_2210;
wire   [15:0] select_ln65_242_fu_1591_p3;
reg   [15:0] select_ln65_242_reg_2216;
wire   [15:0] select_ln65_243_fu_1611_p3;
reg   [15:0] select_ln65_243_reg_2222;
wire   [15:0] select_ln65_245_fu_1631_p3;
reg   [15:0] select_ln65_245_reg_2228;
wire   [15:0] select_ln65_246_fu_1651_p3;
reg   [15:0] select_ln65_246_reg_2234;
wire   [15:0] select_ln65_248_fu_1671_p3;
reg   [15:0] select_ln65_248_reg_2240;
wire   [15:0] select_ln65_249_fu_1691_p3;
reg   [15:0] select_ln65_249_reg_2246;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_265_p4;
wire   [31:0] add_ln86_fu_1717_p2;
reg   [31:0] ap_phi_reg_pp0_iter1_storemerge_reg_261;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_reg_261;
wire   [31:0] add_ln80_fu_376_p2;
wire   [31:0] add_ln76_fu_322_p2;
wire   [31:0] add_ln91_fu_348_p2;
wire   [15:0] shift_buffer_V_fu_405_p1;
wire   [15:0] shift_buffer_V_272_fu_429_p4;
wire   [15:0] shift_buffer_V_273_fu_439_p4;
wire   [15:0] shift_buffer_V_274_fu_449_p4;
wire   [15:0] shift_buffer_V_275_fu_459_p4;
wire   [15:0] shift_buffer_V_276_fu_469_p4;
wire   [15:0] shift_buffer_V_277_fu_479_p4;
wire   [15:0] shift_buffer_V_278_fu_489_p4;
wire   [15:0] shift_buffer_V_279_fu_499_p4;
wire   [15:0] shift_buffer_V_280_fu_509_p4;
wire   [15:0] shift_buffer_V_281_fu_519_p4;
wire   [15:0] shift_buffer_V_282_fu_529_p4;
wire   [15:0] shift_buffer_V_283_fu_539_p4;
wire   [15:0] shift_buffer_V_284_fu_549_p4;
wire   [15:0] shift_buffer_V_285_fu_409_p4;
wire   [15:0] shift_buffer_V_286_fu_419_p4;
reg   [6:0] indvar_flatten_fu_244;
wire   [6:0] add_ln109_fu_286_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] select_ln91_fu_340_p3;
wire   [0:0] and_ln55_fu_1049_p2;
wire   [0:0] icmp_ln55_4_fu_1043_p2;
wire   [0:0] icmp_ln1697_fu_1059_p2;
wire   [0:0] xor_ln1697_fu_1065_p2;
wire   [0:0] icmp_ln1697_211_fu_1079_p2;
wire   [0:0] xor_ln1697_211_fu_1085_p2;
wire   [0:0] icmp_ln1697_213_fu_1099_p2;
wire   [0:0] xor_ln1697_213_fu_1105_p2;
wire   [0:0] icmp_ln1697_214_fu_1119_p2;
wire   [0:0] xor_ln1697_214_fu_1125_p2;
wire   [0:0] icmp_ln1697_216_fu_1139_p2;
wire   [0:0] xor_ln1697_216_fu_1145_p2;
wire   [0:0] icmp_ln1697_217_fu_1159_p2;
wire   [0:0] xor_ln1697_217_fu_1165_p2;
wire   [0:0] icmp_ln1697_219_fu_1179_p2;
wire   [0:0] xor_ln1697_219_fu_1185_p2;
wire   [0:0] icmp_ln1697_220_fu_1199_p2;
wire   [0:0] xor_ln1697_220_fu_1205_p2;
wire   [0:0] icmp_ln1697_222_fu_1219_p2;
wire   [0:0] xor_ln1697_222_fu_1225_p2;
wire   [0:0] icmp_ln1697_223_fu_1239_p2;
wire   [0:0] xor_ln1697_223_fu_1245_p2;
wire   [0:0] icmp_ln1697_225_fu_1259_p2;
wire   [0:0] xor_ln1697_225_fu_1265_p2;
wire   [0:0] icmp_ln1697_226_fu_1279_p2;
wire   [0:0] xor_ln1697_226_fu_1285_p2;
wire   [0:0] icmp_ln1697_228_fu_1299_p2;
wire   [0:0] xor_ln1697_228_fu_1305_p2;
wire   [0:0] icmp_ln1697_229_fu_1319_p2;
wire   [0:0] xor_ln1697_229_fu_1325_p2;
wire   [0:0] icmp_ln1697_231_fu_1339_p2;
wire   [0:0] xor_ln1697_231_fu_1345_p2;
wire   [0:0] icmp_ln1697_232_fu_1359_p2;
wire   [0:0] xor_ln1697_232_fu_1365_p2;
wire   [0:0] icmp_ln1697_234_fu_1379_p2;
wire   [0:0] xor_ln1697_234_fu_1385_p2;
wire   [0:0] icmp_ln1697_235_fu_1399_p2;
wire   [0:0] xor_ln1697_235_fu_1405_p2;
wire   [0:0] icmp_ln1697_237_fu_1419_p2;
wire   [0:0] xor_ln1697_237_fu_1425_p2;
wire   [0:0] icmp_ln1697_238_fu_1439_p2;
wire   [0:0] xor_ln1697_238_fu_1445_p2;
wire   [0:0] icmp_ln1697_240_fu_1459_p2;
wire   [0:0] xor_ln1697_240_fu_1465_p2;
wire   [0:0] icmp_ln1697_241_fu_1479_p2;
wire   [0:0] xor_ln1697_241_fu_1485_p2;
wire   [0:0] icmp_ln1697_243_fu_1499_p2;
wire   [0:0] xor_ln1697_243_fu_1505_p2;
wire   [0:0] icmp_ln1697_244_fu_1519_p2;
wire   [0:0] xor_ln1697_244_fu_1525_p2;
wire   [0:0] icmp_ln1697_246_fu_1539_p2;
wire   [0:0] xor_ln1697_246_fu_1545_p2;
wire   [0:0] icmp_ln1697_247_fu_1559_p2;
wire   [0:0] xor_ln1697_247_fu_1565_p2;
wire   [0:0] icmp_ln1697_249_fu_1579_p2;
wire   [0:0] xor_ln1697_249_fu_1585_p2;
wire   [0:0] icmp_ln1697_250_fu_1599_p2;
wire   [0:0] xor_ln1697_250_fu_1605_p2;
wire   [0:0] icmp_ln1697_252_fu_1619_p2;
wire   [0:0] xor_ln1697_252_fu_1625_p2;
wire   [0:0] icmp_ln1697_253_fu_1639_p2;
wire   [0:0] xor_ln1697_253_fu_1645_p2;
wire   [0:0] icmp_ln1697_255_fu_1659_p2;
wire   [0:0] xor_ln1697_255_fu_1665_p2;
wire   [0:0] icmp_ln1697_256_fu_1679_p2;
wire   [0:0] xor_ln1697_256_fu_1685_p2;
wire   [0:0] icmp_ln86_fu_1703_p2;
wire   [31:0] select_ln86_fu_1709_p3;
wire   [0:0] icmp_ln1697_212_fu_1730_p2;
wire   [0:0] xor_ln1697_212_fu_1734_p2;
wire   [0:0] icmp_ln1697_215_fu_1746_p2;
wire   [0:0] xor_ln1697_215_fu_1750_p2;
wire   [0:0] icmp_ln1697_218_fu_1762_p2;
wire   [0:0] xor_ln1697_218_fu_1766_p2;
wire   [0:0] icmp_ln1697_221_fu_1778_p2;
wire   [0:0] xor_ln1697_221_fu_1782_p2;
wire   [0:0] icmp_ln1697_224_fu_1794_p2;
wire   [0:0] xor_ln1697_224_fu_1798_p2;
wire   [0:0] icmp_ln1697_227_fu_1810_p2;
wire   [0:0] xor_ln1697_227_fu_1814_p2;
wire   [0:0] icmp_ln1697_230_fu_1826_p2;
wire   [0:0] xor_ln1697_230_fu_1830_p2;
wire   [0:0] icmp_ln1697_233_fu_1842_p2;
wire   [0:0] xor_ln1697_233_fu_1846_p2;
wire   [0:0] icmp_ln1697_236_fu_1858_p2;
wire   [0:0] xor_ln1697_236_fu_1862_p2;
wire   [0:0] icmp_ln1697_239_fu_1874_p2;
wire   [0:0] xor_ln1697_239_fu_1878_p2;
wire   [0:0] icmp_ln1697_242_fu_1890_p2;
wire   [0:0] xor_ln1697_242_fu_1894_p2;
wire   [0:0] icmp_ln1697_245_fu_1906_p2;
wire   [0:0] xor_ln1697_245_fu_1910_p2;
wire   [0:0] icmp_ln1697_248_fu_1922_p2;
wire   [0:0] xor_ln1697_248_fu_1926_p2;
wire   [0:0] icmp_ln1697_251_fu_1938_p2;
wire   [0:0] xor_ln1697_251_fu_1942_p2;
wire   [0:0] icmp_ln1697_254_fu_1954_p2;
wire   [0:0] xor_ln1697_254_fu_1958_p2;
wire   [0:0] icmp_ln1697_257_fu_1970_p2;
wire   [0:0] xor_ln1697_257_fu_1974_p2;
wire   [15:0] select_ln65_250_fu_1980_p3;
wire   [15:0] select_ln65_247_fu_1964_p3;
wire   [15:0] select_ln65_244_fu_1948_p3;
wire   [15:0] select_ln65_241_fu_1932_p3;
wire   [15:0] select_ln65_238_fu_1916_p3;
wire   [15:0] select_ln65_235_fu_1900_p3;
wire   [15:0] select_ln65_232_fu_1884_p3;
wire   [15:0] select_ln65_229_fu_1868_p3;
wire   [15:0] select_ln65_226_fu_1852_p3;
wire   [15:0] select_ln65_223_fu_1836_p3;
wire   [15:0] select_ln65_220_fu_1820_p3;
wire   [15:0] select_ln65_217_fu_1804_p3;
wire   [15:0] res_pack_data_9_fu_1788_p3;
wire   [15:0] res_pack_data_8_fu_1772_p3;
wire   [15:0] res_pack_data_7_fu_1756_p3;
wire   [15:0] res_pack_data_fu_1740_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_392;
reg    ap_condition_390;
reg    ap_condition_529;
reg    ap_condition_416;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 sY_4 = 32'd0;
#0 pY_4 = 32'd0;
#0 pX_4 = 32'd0;
#0 sX_4 = 32'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_167 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_168 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_169 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_170 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_171 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_172 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_173 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_174 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_175 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_176 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_177 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_178 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_179 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_180 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_181 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_182 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_183 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_184 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_185 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_186 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_187 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_188 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_189 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_190 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_191 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_192 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_193 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_194 = 16'd0;
end

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_we0),
    .d0(shift_buffer_V_fu_405_p1),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_ce0),
    .we0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_we0),
    .d0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_d0),
    .q0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_ce0),
    .we0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_we0),
    .d0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_d0),
    .q0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_ce0),
    .we0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_we0),
    .d0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_d0),
    .q0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_ce0),
    .we0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_we0),
    .d0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_d0),
    .q0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_ce0),
    .we0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_we0),
    .d0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_d0),
    .q0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_q0)
);

AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s_void_pooling2d_clelP #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_ce0),
    .we0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_we0),
    .d0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_d0),
    .q0(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_q0)
);

AlexNet_Cifar10_Keras_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_390)) begin
        if ((1'b1 == ap_condition_392)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_261 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_261 <= ap_phi_reg_pp0_iter0_storemerge_reg_261;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_390)) begin
        if ((icmp_ln109_fu_280_p2 == 1'd0)) begin
            indvar_flatten_fu_244 <= add_ln109_fu_286_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_244 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_529)) begin
        if ((icmp_ln76_fu_328_p2 == 1'd1)) begin
            pX_4 <= 32'd0;
        end else if ((icmp_ln76_fu_328_p2 == 1'd0)) begin
            pX_4 <= add_ln76_fu_322_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_416)) begin
        if ((icmp_ln80_fu_382_p2 == 1'd1)) begin
            pY_4 <= 32'd0;
        end else if ((icmp_ln80_fu_382_p2 == 1'd0)) begin
            pY_4 <= add_ln80_fu_376_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_529)) begin
        if ((icmp_ln76_fu_328_p2 == 1'd1)) begin
            sX_4 <= 32'd0;
        end else if ((icmp_ln76_fu_328_p2 == 1'd0)) begin
            sX_4 <= add_ln91_fu_348_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln55_reg_2034 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln55_2_reg_2056 <= and_ln55_2_fu_1053_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln109_reg_2030 <= icmp_ln109_fu_280_p2;
        icmp_ln55_reg_2034_pp0_iter1_reg <= icmp_ln55_reg_2034;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_280_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln55_fu_296_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln55_5_reg_2038 <= icmp_ln55_5_fu_310_p2;
        icmp_ln55_6_reg_2043 <= icmp_ln55_6_fu_316_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_280_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln55_reg_2034 <= icmp_ln55_fu_296_p2;
        icmp_ln76_reg_2048 <= icmp_ln76_fu_328_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_280_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln76_fu_328_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln80_reg_2052 <= icmp_ln80_fu_382_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163 <= void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164 <= void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165 <= void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166 <= void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_167 <= void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_168 <= void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_169 <= void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_170 <= void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_171 <= void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_172 <= void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_173 <= p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_174 <= p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_175 <= p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_176 <= p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_177 <= p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_178 <= p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_q0;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_179 <= shift_buffer_V_fu_405_p1;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_180 <= {{layer23_out_dout[31:16]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_181 <= {{layer23_out_dout[47:32]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_182 <= {{layer23_out_dout[63:48]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_183 <= {{layer23_out_dout[79:64]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_184 <= {{layer23_out_dout[95:80]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_185 <= {{layer23_out_dout[111:96]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_186 <= {{layer23_out_dout[127:112]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_187 <= {{layer23_out_dout[143:128]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_188 <= {{layer23_out_dout[159:144]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_189 <= {{layer23_out_dout[175:160]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_190 <= {{layer23_out_dout[191:176]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_191 <= {{layer23_out_dout[207:192]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_192 <= {{layer23_out_dout[223:208]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_193 <= {{layer23_out_dout[239:224]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_194 <= {{layer23_out_dout[255:240]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln76_reg_2048 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sY_4 <= ap_phi_mux_storemerge_phi_fu_265_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln55_2_fu_1053_p2) & (icmp_ln55_reg_2034 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln65_204_reg_2066 <= select_ln65_204_fu_1091_p3;
        select_ln65_206_reg_2072 <= select_ln65_206_fu_1111_p3;
        select_ln65_207_reg_2078 <= select_ln65_207_fu_1131_p3;
        select_ln65_209_reg_2084 <= select_ln65_209_fu_1151_p3;
        select_ln65_210_reg_2090 <= select_ln65_210_fu_1171_p3;
        select_ln65_212_reg_2096 <= select_ln65_212_fu_1191_p3;
        select_ln65_213_reg_2102 <= select_ln65_213_fu_1211_p3;
        select_ln65_215_reg_2108 <= select_ln65_215_fu_1231_p3;
        select_ln65_216_reg_2114 <= select_ln65_216_fu_1251_p3;
        select_ln65_218_reg_2120 <= select_ln65_218_fu_1271_p3;
        select_ln65_219_reg_2126 <= select_ln65_219_fu_1291_p3;
        select_ln65_221_reg_2132 <= select_ln65_221_fu_1311_p3;
        select_ln65_222_reg_2138 <= select_ln65_222_fu_1331_p3;
        select_ln65_224_reg_2144 <= select_ln65_224_fu_1351_p3;
        select_ln65_225_reg_2150 <= select_ln65_225_fu_1371_p3;
        select_ln65_227_reg_2156 <= select_ln65_227_fu_1391_p3;
        select_ln65_228_reg_2162 <= select_ln65_228_fu_1411_p3;
        select_ln65_230_reg_2168 <= select_ln65_230_fu_1431_p3;
        select_ln65_231_reg_2174 <= select_ln65_231_fu_1451_p3;
        select_ln65_233_reg_2180 <= select_ln65_233_fu_1471_p3;
        select_ln65_234_reg_2186 <= select_ln65_234_fu_1491_p3;
        select_ln65_236_reg_2192 <= select_ln65_236_fu_1511_p3;
        select_ln65_237_reg_2198 <= select_ln65_237_fu_1531_p3;
        select_ln65_239_reg_2204 <= select_ln65_239_fu_1551_p3;
        select_ln65_240_reg_2210 <= select_ln65_240_fu_1571_p3;
        select_ln65_242_reg_2216 <= select_ln65_242_fu_1591_p3;
        select_ln65_243_reg_2222 <= select_ln65_243_fu_1611_p3;
        select_ln65_245_reg_2228 <= select_ln65_245_fu_1631_p3;
        select_ln65_246_reg_2234 <= select_ln65_246_fu_1651_p3;
        select_ln65_248_reg_2240 <= select_ln65_248_fu_1671_p3;
        select_ln65_249_reg_2246 <= select_ln65_249_fu_1691_p3;
        select_ln65_reg_2060 <= select_ln65_fu_1071_p3;
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_280_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_reg_2052 == 1'd0) & (icmp_ln76_reg_2048 == 1'd1) & (icmp_ln109_reg_2030 == 1'd0))) begin
        ap_phi_mux_storemerge_phi_fu_265_p4 = add_ln86_fu_1717_p2;
    end else begin
        ap_phi_mux_storemerge_phi_fu_265_p4 = ap_phi_reg_pp0_iter1_storemerge_reg_261;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_244;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer23_out_blk_n = layer23_out_empty_n;
    end else begin
        layer23_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer23_out_read = 1'b1;
    end else begin
        layer23_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op300_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer24_out_blk_n = layer24_out_full_n;
    end else begin
        layer24_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op300_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer24_out_write = 1'b1;
    end else begin
        layer24_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_we0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_we0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_we0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_we0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_we0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_we0 = 1'd1;
    end else begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_286_p2 = (ap_sig_allocacmp_indvar_flatten_load + 7'd1);

assign add_ln76_fu_322_p2 = (pX_4 + 32'd1);

assign add_ln80_fu_376_p2 = (pY_4 + 32'd1);

assign add_ln86_fu_1717_p2 = (sY_4 + select_ln86_fu_1709_p3);

assign add_ln91_fu_348_p2 = (sX_4 + select_ln91_fu_340_p3);

assign and_ln55_2_fu_1053_p2 = (icmp_ln55_4_fu_1043_p2 & and_ln55_fu_1049_p2);

assign and_ln55_fu_1049_p2 = (icmp_ln55_6_reg_2043 & icmp_ln55_5_reg_2038);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_predicate_op300_write_state3 == 1'b1) & (layer24_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer23_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_predicate_op300_write_state3 == 1'b1) & (layer24_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer23_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_predicate_op300_write_state3 == 1'b1) & (layer24_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer23_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer23_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op300_write_state3 == 1'b1) & (layer24_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_390 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_392 = ((icmp_ln109_fu_280_p2 == 1'd0) & (icmp_ln80_fu_382_p2 == 1'd1) & (icmp_ln76_fu_328_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_416 = ((icmp_ln109_fu_280_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln76_fu_328_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_529 = ((icmp_ln109_fu_280_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_storemerge_reg_261 = 'bx;

always @ (*) begin
    ap_predicate_op300_write_state3 = ((1'd1 == and_ln55_2_reg_2056) & (icmp_ln55_reg_2034_pp0_iter1_reg == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln109_fu_280_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln1697_211_fu_1079_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_179) < $signed(shift_buffer_V_fu_405_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1697_212_fu_1730_p2 = (($signed(select_ln65_reg_2060) < $signed(select_ln65_204_reg_2066)) ? 1'b1 : 1'b0);

assign icmp_ln1697_213_fu_1099_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164) < $signed(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_214_fu_1119_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_180) < $signed(shift_buffer_V_272_fu_429_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_215_fu_1746_p2 = (($signed(select_ln65_206_reg_2072) < $signed(select_ln65_207_reg_2078)) ? 1'b1 : 1'b0);

assign icmp_ln1697_216_fu_1139_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165) < $signed(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_217_fu_1159_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_181) < $signed(shift_buffer_V_273_fu_439_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_218_fu_1762_p2 = (($signed(select_ln65_209_reg_2084) < $signed(select_ln65_210_reg_2090)) ? 1'b1 : 1'b0);

assign icmp_ln1697_219_fu_1179_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166) < $signed(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_220_fu_1199_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_182) < $signed(shift_buffer_V_274_fu_449_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_221_fu_1778_p2 = (($signed(select_ln65_212_reg_2096) < $signed(select_ln65_213_reg_2102)) ? 1'b1 : 1'b0);

assign icmp_ln1697_222_fu_1219_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_167) < $signed(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_223_fu_1239_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_183) < $signed(shift_buffer_V_275_fu_459_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_224_fu_1794_p2 = (($signed(select_ln65_215_reg_2108) < $signed(select_ln65_216_reg_2114)) ? 1'b1 : 1'b0);

assign icmp_ln1697_225_fu_1259_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_168) < $signed(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_226_fu_1279_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_184) < $signed(shift_buffer_V_276_fu_469_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_227_fu_1810_p2 = (($signed(select_ln65_218_reg_2120) < $signed(select_ln65_219_reg_2126)) ? 1'b1 : 1'b0);

assign icmp_ln1697_228_fu_1299_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_169) < $signed(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_229_fu_1319_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_185) < $signed(shift_buffer_V_277_fu_479_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_230_fu_1826_p2 = (($signed(select_ln65_221_reg_2132) < $signed(select_ln65_222_reg_2138)) ? 1'b1 : 1'b0);

assign icmp_ln1697_231_fu_1339_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_170) < $signed(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_232_fu_1359_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_186) < $signed(shift_buffer_V_278_fu_489_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_233_fu_1842_p2 = (($signed(select_ln65_224_reg_2144) < $signed(select_ln65_225_reg_2150)) ? 1'b1 : 1'b0);

assign icmp_ln1697_234_fu_1379_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_171) < $signed(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_235_fu_1399_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_187) < $signed(shift_buffer_V_279_fu_499_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_236_fu_1858_p2 = (($signed(select_ln65_227_reg_2156) < $signed(select_ln65_228_reg_2162)) ? 1'b1 : 1'b0);

assign icmp_ln1697_237_fu_1419_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_172) < $signed(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_238_fu_1439_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_188) < $signed(shift_buffer_V_280_fu_509_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_239_fu_1874_p2 = (($signed(select_ln65_230_reg_2168) < $signed(select_ln65_231_reg_2174)) ? 1'b1 : 1'b0);

assign icmp_ln1697_240_fu_1459_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_173) < $signed(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_241_fu_1479_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_189) < $signed(shift_buffer_V_281_fu_519_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_242_fu_1890_p2 = (($signed(select_ln65_233_reg_2180) < $signed(select_ln65_234_reg_2186)) ? 1'b1 : 1'b0);

assign icmp_ln1697_243_fu_1499_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_174) < $signed(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_244_fu_1519_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_190) < $signed(shift_buffer_V_282_fu_529_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_245_fu_1906_p2 = (($signed(select_ln65_236_reg_2192) < $signed(select_ln65_237_reg_2198)) ? 1'b1 : 1'b0);

assign icmp_ln1697_246_fu_1539_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_175) < $signed(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_247_fu_1559_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_191) < $signed(shift_buffer_V_283_fu_539_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_248_fu_1922_p2 = (($signed(select_ln65_239_reg_2204) < $signed(select_ln65_240_reg_2210)) ? 1'b1 : 1'b0);

assign icmp_ln1697_249_fu_1579_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_176) < $signed(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_250_fu_1599_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_192) < $signed(shift_buffer_V_284_fu_549_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_251_fu_1938_p2 = (($signed(select_ln65_242_reg_2216) < $signed(select_ln65_243_reg_2222)) ? 1'b1 : 1'b0);

assign icmp_ln1697_252_fu_1619_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_177) < $signed(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_253_fu_1639_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_193) < $signed(shift_buffer_V_285_fu_409_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_254_fu_1954_p2 = (($signed(select_ln65_245_reg_2228) < $signed(select_ln65_246_reg_2234)) ? 1'b1 : 1'b0);

assign icmp_ln1697_255_fu_1659_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_178) < $signed(p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1697_256_fu_1679_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_194) < $signed(shift_buffer_V_286_fu_419_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1697_257_fu_1970_p2 = (($signed(select_ln65_248_reg_2240) < $signed(select_ln65_249_reg_2246)) ? 1'b1 : 1'b0);

assign icmp_ln1697_fu_1059_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163) < $signed(void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_q0)) ? 1'b1 : 1'b0);

assign icmp_ln55_4_fu_1043_p2 = ((sY_4 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln55_5_fu_310_p2 = (($signed(pY_4) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_6_fu_316_p2 = (($signed(pX_4) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_296_p2 = ((sX_4 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_328_p2 = ((add_ln76_fu_322_p2 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_382_p2 = ((add_ln80_fu_376_p2 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_1703_p2 = ((sY_4 == 32'd1) ? 1'b1 : 1'b0);

assign layer24_out_din = {{{{{{{{{{{{{{{{select_ln65_250_fu_1980_p3}, {select_ln65_247_fu_1964_p3}}, {select_ln65_244_fu_1948_p3}}, {select_ln65_241_fu_1932_p3}}, {select_ln65_238_fu_1916_p3}}, {select_ln65_235_fu_1900_p3}}, {select_ln65_232_fu_1884_p3}}, {select_ln65_229_fu_1868_p3}}, {select_ln65_226_fu_1852_p3}}, {select_ln65_223_fu_1836_p3}}, {select_ln65_220_fu_1820_p3}}, {select_ln65_217_fu_1804_p3}}, {res_pack_data_9_fu_1788_p3}}, {res_pack_data_8_fu_1772_p3}}, {res_pack_data_7_fu_1756_p3}}, {res_pack_data_fu_1740_p3}};

assign p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_d0 = {{layer23_out_dout[255:240]}};

assign p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_d0 = {{layer23_out_dout[239:224]}};

assign p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_d0 = {{layer23_out_dout[223:208]}};

assign p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_d0 = {{layer23_out_dout[207:192]}};

assign p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_d0 = {{layer23_out_dout[191:176]}};

assign p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_d0 = {{layer23_out_dout[175:160]}};

assign res_pack_data_7_fu_1756_p3 = ((xor_ln1697_215_fu_1750_p2[0:0] == 1'b1) ? select_ln65_206_reg_2072 : select_ln65_207_reg_2078);

assign res_pack_data_8_fu_1772_p3 = ((xor_ln1697_218_fu_1766_p2[0:0] == 1'b1) ? select_ln65_209_reg_2084 : select_ln65_210_reg_2090);

assign res_pack_data_9_fu_1788_p3 = ((xor_ln1697_221_fu_1782_p2[0:0] == 1'b1) ? select_ln65_212_reg_2096 : select_ln65_213_reg_2102);

assign res_pack_data_fu_1740_p3 = ((xor_ln1697_212_fu_1734_p2[0:0] == 1'b1) ? select_ln65_reg_2060 : select_ln65_204_reg_2066);

assign select_ln65_204_fu_1091_p3 = ((xor_ln1697_211_fu_1085_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_179 : shift_buffer_V_fu_405_p1);

assign select_ln65_206_fu_1111_p3 = ((xor_ln1697_213_fu_1105_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164 : void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_q0);

assign select_ln65_207_fu_1131_p3 = ((xor_ln1697_214_fu_1125_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_180 : shift_buffer_V_272_fu_429_p4);

assign select_ln65_209_fu_1151_p3 = ((xor_ln1697_216_fu_1145_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165 : void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_q0);

assign select_ln65_210_fu_1171_p3 = ((xor_ln1697_217_fu_1165_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_181 : shift_buffer_V_273_fu_439_p4);

assign select_ln65_212_fu_1191_p3 = ((xor_ln1697_219_fu_1185_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166 : void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_q0);

assign select_ln65_213_fu_1211_p3 = ((xor_ln1697_220_fu_1205_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_182 : shift_buffer_V_274_fu_449_p4);

assign select_ln65_215_fu_1231_p3 = ((xor_ln1697_222_fu_1225_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_167 : void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_q0);

assign select_ln65_216_fu_1251_p3 = ((xor_ln1697_223_fu_1245_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_183 : shift_buffer_V_275_fu_459_p4);

assign select_ln65_217_fu_1804_p3 = ((xor_ln1697_224_fu_1798_p2[0:0] == 1'b1) ? select_ln65_215_reg_2108 : select_ln65_216_reg_2114);

assign select_ln65_218_fu_1271_p3 = ((xor_ln1697_225_fu_1265_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_168 : void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_q0);

assign select_ln65_219_fu_1291_p3 = ((xor_ln1697_226_fu_1285_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_184 : shift_buffer_V_276_fu_469_p4);

assign select_ln65_220_fu_1820_p3 = ((xor_ln1697_227_fu_1814_p2[0:0] == 1'b1) ? select_ln65_218_reg_2120 : select_ln65_219_reg_2126);

assign select_ln65_221_fu_1311_p3 = ((xor_ln1697_228_fu_1305_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_169 : void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_q0);

assign select_ln65_222_fu_1331_p3 = ((xor_ln1697_229_fu_1325_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_185 : shift_buffer_V_277_fu_479_p4);

assign select_ln65_223_fu_1836_p3 = ((xor_ln1697_230_fu_1830_p2[0:0] == 1'b1) ? select_ln65_221_reg_2132 : select_ln65_222_reg_2138);

assign select_ln65_224_fu_1351_p3 = ((xor_ln1697_231_fu_1345_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_170 : void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_q0);

assign select_ln65_225_fu_1371_p3 = ((xor_ln1697_232_fu_1365_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_186 : shift_buffer_V_278_fu_489_p4);

assign select_ln65_226_fu_1852_p3 = ((xor_ln1697_233_fu_1846_p2[0:0] == 1'b1) ? select_ln65_224_reg_2144 : select_ln65_225_reg_2150);

assign select_ln65_227_fu_1391_p3 = ((xor_ln1697_234_fu_1385_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_171 : void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_q0);

assign select_ln65_228_fu_1411_p3 = ((xor_ln1697_235_fu_1405_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_187 : shift_buffer_V_279_fu_499_p4);

assign select_ln65_229_fu_1868_p3 = ((xor_ln1697_236_fu_1862_p2[0:0] == 1'b1) ? select_ln65_227_reg_2156 : select_ln65_228_reg_2162);

assign select_ln65_230_fu_1431_p3 = ((xor_ln1697_237_fu_1425_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_172 : void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_q0);

assign select_ln65_231_fu_1451_p3 = ((xor_ln1697_238_fu_1445_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_188 : shift_buffer_V_280_fu_509_p4);

assign select_ln65_232_fu_1884_p3 = ((xor_ln1697_239_fu_1878_p2[0:0] == 1'b1) ? select_ln65_230_reg_2168 : select_ln65_231_reg_2174);

assign select_ln65_233_fu_1471_p3 = ((xor_ln1697_240_fu_1465_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_173 : p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_59_q0);

assign select_ln65_234_fu_1491_p3 = ((xor_ln1697_241_fu_1485_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_189 : shift_buffer_V_281_fu_519_p4);

assign select_ln65_235_fu_1900_p3 = ((xor_ln1697_242_fu_1894_p2[0:0] == 1'b1) ? select_ln65_233_reg_2180 : select_ln65_234_reg_2186);

assign select_ln65_236_fu_1511_p3 = ((xor_ln1697_243_fu_1505_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_174 : p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_58_q0);

assign select_ln65_237_fu_1531_p3 = ((xor_ln1697_244_fu_1525_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_190 : shift_buffer_V_282_fu_529_p4);

assign select_ln65_238_fu_1916_p3 = ((xor_ln1697_245_fu_1910_p2[0:0] == 1'b1) ? select_ln65_236_reg_2192 : select_ln65_237_reg_2198);

assign select_ln65_239_fu_1551_p3 = ((xor_ln1697_246_fu_1545_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_175 : p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_57_q0);

assign select_ln65_240_fu_1571_p3 = ((xor_ln1697_247_fu_1565_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_191 : shift_buffer_V_283_fu_539_p4);

assign select_ln65_241_fu_1932_p3 = ((xor_ln1697_248_fu_1926_p2[0:0] == 1'b1) ? select_ln65_239_reg_2204 : select_ln65_240_reg_2210);

assign select_ln65_242_fu_1591_p3 = ((xor_ln1697_249_fu_1585_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_176 : p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_56_q0);

assign select_ln65_243_fu_1611_p3 = ((xor_ln1697_250_fu_1605_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_192 : shift_buffer_V_284_fu_549_p4);

assign select_ln65_244_fu_1948_p3 = ((xor_ln1697_251_fu_1942_p2[0:0] == 1'b1) ? select_ln65_242_reg_2216 : select_ln65_243_reg_2222);

assign select_ln65_245_fu_1631_p3 = ((xor_ln1697_252_fu_1625_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_177 : p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_55_q0);

assign select_ln65_246_fu_1651_p3 = ((xor_ln1697_253_fu_1645_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_193 : shift_buffer_V_285_fu_409_p4);

assign select_ln65_247_fu_1964_p3 = ((xor_ln1697_254_fu_1958_p2[0:0] == 1'b1) ? select_ln65_245_reg_2228 : select_ln65_246_reg_2234);

assign select_ln65_248_fu_1671_p3 = ((xor_ln1697_255_fu_1665_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_178 : p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3EL_54_q0);

assign select_ln65_249_fu_1691_p3 = ((xor_ln1697_256_fu_1685_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_194 : shift_buffer_V_286_fu_419_p4);

assign select_ln65_250_fu_1980_p3 = ((xor_ln1697_257_fu_1974_p2[0:0] == 1'b1) ? select_ln65_248_reg_2240 : select_ln65_249_reg_2246);

assign select_ln65_fu_1071_p3 = ((xor_ln1697_fu_1065_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163 : void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_9_q0);

assign select_ln86_fu_1709_p3 = ((icmp_ln86_fu_1703_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign select_ln91_fu_340_p3 = ((icmp_ln55_fu_296_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign shift_buffer_V_272_fu_429_p4 = {{layer23_out_dout[31:16]}};

assign shift_buffer_V_273_fu_439_p4 = {{layer23_out_dout[47:32]}};

assign shift_buffer_V_274_fu_449_p4 = {{layer23_out_dout[63:48]}};

assign shift_buffer_V_275_fu_459_p4 = {{layer23_out_dout[79:64]}};

assign shift_buffer_V_276_fu_469_p4 = {{layer23_out_dout[95:80]}};

assign shift_buffer_V_277_fu_479_p4 = {{layer23_out_dout[111:96]}};

assign shift_buffer_V_278_fu_489_p4 = {{layer23_out_dout[127:112]}};

assign shift_buffer_V_279_fu_499_p4 = {{layer23_out_dout[143:128]}};

assign shift_buffer_V_280_fu_509_p4 = {{layer23_out_dout[159:144]}};

assign shift_buffer_V_281_fu_519_p4 = {{layer23_out_dout[175:160]}};

assign shift_buffer_V_282_fu_529_p4 = {{layer23_out_dout[191:176]}};

assign shift_buffer_V_283_fu_539_p4 = {{layer23_out_dout[207:192]}};

assign shift_buffer_V_284_fu_549_p4 = {{layer23_out_dout[223:208]}};

assign shift_buffer_V_285_fu_409_p4 = {{layer23_out_dout[239:224]}};

assign shift_buffer_V_286_fu_419_p4 = {{layer23_out_dout[255:240]}};

assign shift_buffer_V_fu_405_p1 = layer23_out_dout[15:0];

assign start_out = real_start;

assign void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_1_d0 = {{layer23_out_dout[143:128]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_2_d0 = {{layer23_out_dout[127:112]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_3_d0 = {{layer23_out_dout[111:96]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_4_d0 = {{layer23_out_dout[95:80]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_5_d0 = {{layer23_out_dout[79:64]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_6_d0 = {{layer23_out_dout[63:48]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_7_d0 = {{layer23_out_dout[47:32]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_8_d0 = {{layer23_out_dout[31:16]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_16u_0_line_buffer_d0 = {{layer23_out_dout[159:144]}};

assign xor_ln1697_211_fu_1085_p2 = (icmp_ln1697_211_fu_1079_p2 ^ 1'd1);

assign xor_ln1697_212_fu_1734_p2 = (icmp_ln1697_212_fu_1730_p2 ^ 1'd1);

assign xor_ln1697_213_fu_1105_p2 = (icmp_ln1697_213_fu_1099_p2 ^ 1'd1);

assign xor_ln1697_214_fu_1125_p2 = (icmp_ln1697_214_fu_1119_p2 ^ 1'd1);

assign xor_ln1697_215_fu_1750_p2 = (icmp_ln1697_215_fu_1746_p2 ^ 1'd1);

assign xor_ln1697_216_fu_1145_p2 = (icmp_ln1697_216_fu_1139_p2 ^ 1'd1);

assign xor_ln1697_217_fu_1165_p2 = (icmp_ln1697_217_fu_1159_p2 ^ 1'd1);

assign xor_ln1697_218_fu_1766_p2 = (icmp_ln1697_218_fu_1762_p2 ^ 1'd1);

assign xor_ln1697_219_fu_1185_p2 = (icmp_ln1697_219_fu_1179_p2 ^ 1'd1);

assign xor_ln1697_220_fu_1205_p2 = (icmp_ln1697_220_fu_1199_p2 ^ 1'd1);

assign xor_ln1697_221_fu_1782_p2 = (icmp_ln1697_221_fu_1778_p2 ^ 1'd1);

assign xor_ln1697_222_fu_1225_p2 = (icmp_ln1697_222_fu_1219_p2 ^ 1'd1);

assign xor_ln1697_223_fu_1245_p2 = (icmp_ln1697_223_fu_1239_p2 ^ 1'd1);

assign xor_ln1697_224_fu_1798_p2 = (icmp_ln1697_224_fu_1794_p2 ^ 1'd1);

assign xor_ln1697_225_fu_1265_p2 = (icmp_ln1697_225_fu_1259_p2 ^ 1'd1);

assign xor_ln1697_226_fu_1285_p2 = (icmp_ln1697_226_fu_1279_p2 ^ 1'd1);

assign xor_ln1697_227_fu_1814_p2 = (icmp_ln1697_227_fu_1810_p2 ^ 1'd1);

assign xor_ln1697_228_fu_1305_p2 = (icmp_ln1697_228_fu_1299_p2 ^ 1'd1);

assign xor_ln1697_229_fu_1325_p2 = (icmp_ln1697_229_fu_1319_p2 ^ 1'd1);

assign xor_ln1697_230_fu_1830_p2 = (icmp_ln1697_230_fu_1826_p2 ^ 1'd1);

assign xor_ln1697_231_fu_1345_p2 = (icmp_ln1697_231_fu_1339_p2 ^ 1'd1);

assign xor_ln1697_232_fu_1365_p2 = (icmp_ln1697_232_fu_1359_p2 ^ 1'd1);

assign xor_ln1697_233_fu_1846_p2 = (icmp_ln1697_233_fu_1842_p2 ^ 1'd1);

assign xor_ln1697_234_fu_1385_p2 = (icmp_ln1697_234_fu_1379_p2 ^ 1'd1);

assign xor_ln1697_235_fu_1405_p2 = (icmp_ln1697_235_fu_1399_p2 ^ 1'd1);

assign xor_ln1697_236_fu_1862_p2 = (icmp_ln1697_236_fu_1858_p2 ^ 1'd1);

assign xor_ln1697_237_fu_1425_p2 = (icmp_ln1697_237_fu_1419_p2 ^ 1'd1);

assign xor_ln1697_238_fu_1445_p2 = (icmp_ln1697_238_fu_1439_p2 ^ 1'd1);

assign xor_ln1697_239_fu_1878_p2 = (icmp_ln1697_239_fu_1874_p2 ^ 1'd1);

assign xor_ln1697_240_fu_1465_p2 = (icmp_ln1697_240_fu_1459_p2 ^ 1'd1);

assign xor_ln1697_241_fu_1485_p2 = (icmp_ln1697_241_fu_1479_p2 ^ 1'd1);

assign xor_ln1697_242_fu_1894_p2 = (icmp_ln1697_242_fu_1890_p2 ^ 1'd1);

assign xor_ln1697_243_fu_1505_p2 = (icmp_ln1697_243_fu_1499_p2 ^ 1'd1);

assign xor_ln1697_244_fu_1525_p2 = (icmp_ln1697_244_fu_1519_p2 ^ 1'd1);

assign xor_ln1697_245_fu_1910_p2 = (icmp_ln1697_245_fu_1906_p2 ^ 1'd1);

assign xor_ln1697_246_fu_1545_p2 = (icmp_ln1697_246_fu_1539_p2 ^ 1'd1);

assign xor_ln1697_247_fu_1565_p2 = (icmp_ln1697_247_fu_1559_p2 ^ 1'd1);

assign xor_ln1697_248_fu_1926_p2 = (icmp_ln1697_248_fu_1922_p2 ^ 1'd1);

assign xor_ln1697_249_fu_1585_p2 = (icmp_ln1697_249_fu_1579_p2 ^ 1'd1);

assign xor_ln1697_250_fu_1605_p2 = (icmp_ln1697_250_fu_1599_p2 ^ 1'd1);

assign xor_ln1697_251_fu_1942_p2 = (icmp_ln1697_251_fu_1938_p2 ^ 1'd1);

assign xor_ln1697_252_fu_1625_p2 = (icmp_ln1697_252_fu_1619_p2 ^ 1'd1);

assign xor_ln1697_253_fu_1645_p2 = (icmp_ln1697_253_fu_1639_p2 ^ 1'd1);

assign xor_ln1697_254_fu_1958_p2 = (icmp_ln1697_254_fu_1954_p2 ^ 1'd1);

assign xor_ln1697_255_fu_1665_p2 = (icmp_ln1697_255_fu_1659_p2 ^ 1'd1);

assign xor_ln1697_256_fu_1685_p2 = (icmp_ln1697_256_fu_1679_p2 ^ 1'd1);

assign xor_ln1697_257_fu_1974_p2 = (icmp_ln1697_257_fu_1970_p2 ^ 1'd1);

assign xor_ln1697_fu_1065_p2 = (icmp_ln1697_fu_1059_p2 ^ 1'd1);

endmodule //AlexNet_Cifar10_Keras_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config24_s
